export type MealCategory = 'breakfast' | 'lunchDinner' | 'lowCalorie'

export type Meal = {
  id: string
  category: MealCategory
  description: string
  davidRating: number | null
  lynnRating: number | null
  status: 'notOrdered' | 'ordered' | 'favorite' | 'doNotOrderAgain'
  comments: string
  recommendedBecause: string
  lastOrderedDate: string
  timesOrdered: number
  davidNote?: string
  lynnNote?: string
}

export const meals: Meal[] = [
  {
    "id": "breakfast-herbed-goat-cheese-frittata-or-ricotta-and-sweet-potato-frittata",
    "category": "breakfast",
    "description": "Herbed goat cheese frittata or ricotta and sweet potato frittata",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "Lynn thought it was great, David didn't love the goat cheese - switch to feta or use less goat cheese",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2025-11-30",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-hard-boiled-eggs-with-jalapeno-chickpea-flour-pancakes",
    "category": "breakfast",
    "description": "Hard boiled eggs with jalapeno chickpea flour pancakes",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-white-bean-and-egg-bake-with-herbs",
    "category": "breakfast",
    "description": "White bean and egg bake with herbs",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "❤️",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2025-12-28",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-chickpea-flour-pancakes-with-lemon-hummus-cottage-and-cucumbers",
    "category": "breakfast",
    "description": "Chickpea flour pancakes with lemon hummus cottage and cucumbers",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-07-26",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-hard-boiled-eggs-turkey-bacon-or-chicken-sausage-and-cucumber-tomato-platter",
    "category": "breakfast",
    "description": "Hard boiled eggs/ turkey bacon or chicken sausage and cucumber tomato platter",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "❤️  want more turkey bacon!",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-05-24",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-avocado-egg-and-brown-rice-bowls",
    "category": "breakfast",
    "description": "Avocado egg and brown rice bowls",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-07-12",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-lemon-and-banana-protein-pancake-w-side-of-greek-yogurt-no-flour",
    "category": "breakfast",
    "description": "Lemon and banana protein pancake w side of greek yogurt ( no flour)",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-02-02",
    "timesOrdered": 1,
    "davidNote": "Not a fave",
    "lynnNote": "Not a fave"
  },
  {
    "id": "breakfast-egg-white-and-cheddar-chicken-sausage-frittata",
    "category": "breakfast",
    "description": "Egg white and cheddar chicken sausage frittata",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-02-15",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-tiramisu-protein-overnight-oats",
    "category": "breakfast",
    "description": "Tiramisu protein overnight oats",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "2026-02-22",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-sweet-potato-hash-and-fried-eggs-with-avocado-drizzle",
    "category": "breakfast",
    "description": "Sweet potato hash and fried eggs with avocado drizzle",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-01-19",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-mediterranean-feta-bake-eggs",
    "category": "breakfast",
    "description": "Mediterranean feta bake eggs",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-03-15",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": "Pretty good - like the carrots"
  },
  {
    "id": "breakfast-cottage-cheese-scrambled-eggs-avocado-and-chicken-sausage-links",
    "category": "breakfast",
    "description": "Cottage cheese scrambled eggs avocado and chicken sausage links",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "Lynn ❤️",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-05-10",
    "timesOrdered": 3,
    "davidNote": "",
    "lynnNote": "❤️"
  },
  {
    "id": "breakfast-gluten-free-open-face-quesadilla-spinach-egg-and-cheddar",
    "category": "breakfast",
    "description": "Gluten free open face quesadilla spinach egg and cheddar",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "David didn't like the cheese",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-03-01",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-sweet-potato-toast-with-harissa-chickpeas-or-peanut-butter-and-fresh-fruit-compote",
    "category": "breakfast",
    "description": "Sweet potato toast with harissa chickpeas or peanut butter and fresh fruit compote",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "❤️",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-05-17",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-turmeric-asparagus-pistachio-savory-overnight-oats-with-egg",
    "category": "breakfast",
    "description": "Turmeric asparagus pistachio savory overnight oats ( with egg)",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-greek-yogurt-bowls-fresh-fruit-and-nuts-with-light-granola",
    "category": "breakfast",
    "description": "Greek yogurt bowls fresh fruit and nuts with light granola",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-chicken-sausage-sweet-potato-casserole",
    "category": "breakfast",
    "description": "Chicken sausage sweet potato casserole",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-07-19",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-spinach-chickpeas-and-feta-bake-with-side-of-turkey-bacon",
    "category": "breakfast",
    "description": "Spinach chickpeas and feta bake with ( side of turkey bacon)",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-04-19",
    "timesOrdered": 1,
    "davidNote": "Too many beans",
    "lynnNote": "❤️"
  },
  {
    "id": "breakfast-scrambled-eggs-with-artichokes-capers-rosemary-side-or-chicken-sausage",
    "category": "breakfast",
    "description": "Scrambled eggs with artichokes capers rosemary ( side or chicken sausage)",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "Good- more eggs, less artichoke",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-04-26",
    "timesOrdered": 1,
    "davidNote": "More egg",
    "lynnNote": "More egg"
  },
  {
    "id": "breakfast-pistachio-overnight-protein-oats-pistachio-milk-crushed-pistachios-make-less-dry",
    "category": "breakfast",
    "description": "Pistachio overnight protein oats ( pistachio milk crushed Pistachios make less dry)",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-fresh-fruit-oatmeal-bake-side-of-turkey-bacon",
    "category": "breakfast",
    "description": "Fresh fruit oatmeal bake ( side of turkey bacon)",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-lemon-berry-ricotta-and-cottage-cheese-bowls-with-granola",
    "category": "breakfast",
    "description": "Lemon berry ricotta and cottage cheese bowls with granola",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-everything-bagel-cottage-cheese-bowls-turkey-bacon-eggs-cucumber-radish",
    "category": "breakfast",
    "description": "Everything bagel cottage cheese bowls ( turkey bacon eggs cucumber radish)",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-hashbrown-quiche-veggie-and-turkey-bacon-or-chicken-sausage-cups",
    "category": "breakfast",
    "description": "Hashbrown quiche veggie and turkey bacon or chicken sausage cups",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-open-face-quesadillas-with-egg-sausage-and-american-cheese-corn-tortillas",
    "category": "breakfast",
    "description": "Open face quesadillas with egg sausage and american cheese ( corn tortillas)",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-03-29",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-egg-and-banana-pancakes-with-fresh-fruit-chicken-sausage",
    "category": "breakfast",
    "description": "Egg and banana pancakes with fresh fruit chicken sausage",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-06-21",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-spinach-feta-scrambled-egg-pitas",
    "category": "breakfast",
    "description": "Spinach feta scrambled egg pitas",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "❤️",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-05-03",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-sweet-potato-and-oat-flour-pancakes-with-greek-yogurt-and-berries",
    "category": "breakfast",
    "description": "Sweet potato and oat flour pancakes with greek yogurt and berries",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-egg-and-green-chile-or-egg-and-breakfast-spice-ground-chicken-not-processed-breakfast-burritos-montereyjack-cheddar",
    "category": "breakfast",
    "description": "Egg and green chile or egg and breakfast spice ground chicken (not processed) breakfast burritos* montereyjack/cheddar",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-red-potato-hash-with-green-onion-hard-boiled-eggs-and-avocado",
    "category": "breakfast",
    "description": "Red potato hash with green onion hard boiled eggs and avocado",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-zucchini-feta-egg-frittata",
    "category": "breakfast",
    "description": "Zucchini feta egg frittata",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-carrot-and-raisin-greek-yogurt-muffins-with-side-of-turkey-bacon",
    "category": "breakfast",
    "description": "Carrot and raisin greek yogurt muffins with side of turkey bacon",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-prosciutto-and-spinach-egg-cups",
    "category": "breakfast",
    "description": "Prosciutto and spinach egg cups",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-flourless-egg-and-cheddar-herbed-scones",
    "category": "breakfast",
    "description": "Flourless egg and cheddar herbed scones",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-zucchini-and-parmesan-egg-cups",
    "category": "breakfast",
    "description": "Zucchini and parmesan egg cups",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-08-02",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-sweet-potato-and-beet-hash-with-turkey-bacon-and-hard-boiled-eggs",
    "category": "breakfast",
    "description": "Sweet potato and beet hash with turkey bacon and hard boiled eggs",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-herb-and-ricotta-omelets-side-of-fresh-fruit",
    "category": "breakfast",
    "description": "Herb and ricotta omelets side of fresh fruit",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-curried-scrambled-eggs-with-avocado-and-lentil-dosas",
    "category": "breakfast",
    "description": "Curried scrambled eggs with avocado and lentil dosas",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-egg-and-cottage-cheese-baked-bell-peppers",
    "category": "breakfast",
    "description": "Egg and cottage cheese baked bell peppers",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-egg-and-spinach-breakfast-sandwiches-with-chive-cream-cheese-side-fresh-fruit",
    "category": "breakfast",
    "description": "Egg and spinach breakfast sandwiches with chive cream cheese side fresh fruit",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-everything-bagel-seasoning-egg-cheese-and-veggie-bake",
    "category": "breakfast",
    "description": "Everything bagel seasoning egg cheese and veggie bake",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-herbed-egg-and-cottage-cheese-salad-side-of-cucumber-avocado",
    "category": "breakfast",
    "description": "Herbed egg and cottage cheese salad side of cucumber/ avocado",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-egg-salad-breakfast-pita",
    "category": "breakfast",
    "description": "Egg salad breakfast pita",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-zucchini-and-almond-flour-pancakes-with-greek-yogurt-and-fresh-fruit",
    "category": "breakfast",
    "description": "Zucchini and almond flour pancakes with greek yogurt and fresh fruit",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-baked-sweet-potato-with-everything-bagel-seasoning-scrambled-eggs-avocado",
    "category": "breakfast",
    "description": "Baked sweet potato with everything bagel seasoning scrambled eggs avocado",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-moroccan-spiced-chicken-with-quinoa-and-green-beans",
    "category": "lunchDinner",
    "description": "Moroccan spiced chicken with quinoa and green beans",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-03-15",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": "Good"
  },
  {
    "id": "lunchDinner-mediterranean-turkey-chicken-quinoa-meatballs-with-tahini-roasted-carrots",
    "category": "lunchDinner",
    "description": "Mediterranean turkey & chicken quinoa meatballs with tahini roasted carrots",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-moroccan-lentil-bowls",
    "category": "lunchDinner",
    "description": "Moroccan lentil bowls",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "2026-01-04",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-filet-with-chimichurri-fingerling-potatoes-green-cabbage-salad",
    "category": "lunchDinner",
    "description": "Filet with chimichurri fingerling potatoes green cabbage salad",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2025-12-14",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-beef-harissa-meatballs-with-roasted-chickpeas-and-veggies",
    "category": "lunchDinner",
    "description": "Beef harissa meatballs with roasted chickpeas and veggies",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-turkey-beef-meatloaf-w-fennel-bbq-sauce-mashed-sweet-potato-and-broccolini",
    "category": "lunchDinner",
    "description": "Turkey/ beef meatloaf w fennel bbq sauce mashed sweet potato and broccolini",
    "davidRating": null,
    "lynnRating": null,
    "status": "favorite",
    "comments": "❤️  the brocoli was too chewy",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-05-10",
    "timesOrdered": 2,
    "davidNote": "❤️",
    "lynnNote": "❤️"
  },
  {
    "id": "lunchDinner-roasted-balsamic-chicken-with-white-rice-and-roasted-root-vegetables",
    "category": "lunchDinner",
    "description": "Roasted balsamic chicken with white rice and roasted root vegetables",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "Chicken very tender! Great flavor",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-01-04",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-italian-zucchini-boats-over-a-bed-of-quinoa",
    "category": "lunchDinner",
    "description": "Italian zucchini boats over a bed of quinoa",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-lentil-zucchini-and-mint-salad",
    "category": "lunchDinner",
    "description": "Lentil zucchini and mint salad",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-06-21",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-thai-turkey-and-chicken-meatballs-with-cauliflower-stir-fry-rice",
    "category": "lunchDinner",
    "description": "Thai turkey and chicken meatballs with cauliflower stir fry rice",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "Lynn loved it - David thought meatballs were bland, but loved the cauliflower rice.",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2025-11-30",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-lamb-chops-with-apricot-chutney-mint-sweet-pea-mash-quinoa-with-pistachios",
    "category": "lunchDinner",
    "description": "Lamb chops with apricot chutney mint sweet pea mash quinoa with pistachios",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-01-04",
    "timesOrdered": 2,
    "davidNote": "sub in something besides quinoa",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-filet-with-horseradish-sauce-green-bean-salad-and-sweet-potato-medallions",
    "category": "lunchDinner",
    "description": "Filet with horseradish sauce green bean salad and sweet potato medallions",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "David loved it - would prefer the meat is sliced so it's easier for him to eat",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2025-11-30",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-oven-roasted-chicken-with-chili-spiced-green-beans-and-turmeric-rice",
    "category": "lunchDinner",
    "description": "Oven roasted chicken with chili spiced green beans and turmeric rice",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "❤️ David's favorite chicken",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2025-12-07",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-marinated-oven-roasted-chicken-breast-with-beet-white-bean-and-feta-salad",
    "category": "lunchDinner",
    "description": "Marinated oven roasted chicken breast with beet white bean and feta salad",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "❤️",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-06-07",
    "timesOrdered": 3,
    "davidNote": "w beets but sub in something besides quinoa",
    "lynnNote": "❤️"
  },
  {
    "id": "lunchDinner-chicken-shawarma-skewers-with-spiced-basmati-rice",
    "category": "lunchDinner",
    "description": "Chicken shawarma skewers with spiced basmati rice",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "Good flavor",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2025-11-30",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-ground-chicken-lettuce-wraps-with-basmati-rice",
    "category": "lunchDinner",
    "description": "Ground chicken lettuce wraps with basmati rice",
    "davidRating": null,
    "lynnRating": null,
    "status": "favorite",
    "comments": "❤️  Both liked",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-01-11",
    "timesOrdered": 2,
    "davidNote": "❤️",
    "lynnNote": "❤️"
  },
  {
    "id": "lunchDinner-roast-chicken-fall-harvest-bowl-with-hummus-and-quinoa",
    "category": "lunchDinner",
    "description": "Roast chicken fall harvest bowl with hummus and quinoa",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-buffalo-chicken-with-cauliflower-florets-and-quinoa",
    "category": "lunchDinner",
    "description": "Buffalo chicken with cauliflower florets and quinoa",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-tuscan-chicken-white-bean-and-spinach-stew",
    "category": "lunchDinner",
    "description": "Tuscan chicken white bean and spinach stew",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "❤️",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-03-01",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": "❤️"
  },
  {
    "id": "lunchDinner-shredded-green-chile-chicken-with-cabbage-and-black-beans",
    "category": "lunchDinner",
    "description": "Shredded green chile chicken with cabbage and black beans",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "❤️ Good flavor! Lynn's favorite",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2025-12-28",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-chicken-piccata-with-asparagus-and-baby-potatoes",
    "category": "lunchDinner",
    "description": "Chicken piccata with asparagus and baby potatoes",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "❤️",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-05-03",
    "timesOrdered": 3,
    "davidNote": "❤️",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-chicken-turkey-ragu-marina-with-spaghetti-squash-pasta",
    "category": "lunchDinner",
    "description": "Chicken Turkey ragu marina with spaghetti squash pasta",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "❤️",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-04-05",
    "timesOrdered": 3,
    "davidNote": "",
    "lynnNote": "❤️"
  },
  {
    "id": "lunchDinner-thai-green-curry-chicken-with-bell-peppers-with-basmati-rice",
    "category": "lunchDinner",
    "description": "Thai green curry chicken with bell peppers with basmati rice",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "❤️",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-01-19",
    "timesOrdered": 2,
    "davidNote": "",
    "lynnNote": "❤️"
  },
  {
    "id": "lunchDinner-lemongrass-black-pepper-filet-bites-with-asparagus-and-white-rice",
    "category": "lunchDinner",
    "description": "Lemongrass black pepper filet bites with asparagus and white rice",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "❤️  Like the spice!",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2025-12-28",
    "timesOrdered": 2,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-chicken-salad-w-smashed-cucumbers-chili-crisp-and-jalapeno-hummus",
    "category": "lunchDinner",
    "description": "Chicken salad w smashed cucumbers chili crisp and jalapeno hummus",
    "davidRating": null,
    "lynnRating": null,
    "status": "favorite",
    "comments": "❤️",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-05-17",
    "timesOrdered": 2,
    "davidNote": "❤️",
    "lynnNote": "❤️"
  },
  {
    "id": "lunchDinner-chicken-laab-with-white-rice",
    "category": "lunchDinner",
    "description": "Chicken Laab with white rice",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-03-29",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-braised-chicken-and-cabbage-with-sumac-and-lime-white-rice",
    "category": "lunchDinner",
    "description": "Braised chicken and cabbage with sumac and lime white rice",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "Very good!",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-01-11",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-lemon-pepper-chicken-greek-goddess-bowls-with-white-beans",
    "category": "lunchDinner",
    "description": "Lemon pepper chicken greek goddess bowls with white beans",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "❤️  Dave liked",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-01-11",
    "timesOrdered": 1,
    "davidNote": "❤️",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-filet-jalapeno-cilantro-yogurt-sauce-and-black-bean-and-corn-salad",
    "category": "lunchDinner",
    "description": "Filet jalapeno cilantro yogurt sauce and black bean and corn salad",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-02-09",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-ground-bison-sloppy-joe-stuffed-sweet-potatoes",
    "category": "lunchDinner",
    "description": "Ground bison sloppy joe stuffed sweet potatoes",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "❤️ David thought it was salty. Lots of flavor, though1",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-01-25",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": "❤️"
  },
  {
    "id": "lunchDinner-coconut-chicken-with-peanut-salsa-rice-noodles",
    "category": "lunchDinner",
    "description": "Coconut chicken with peanut salsa rice noodles",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "❤️  Lynn liked",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-01-11",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": "❤️"
  },
  {
    "id": "lunchDinner-spicy-chicken-alvodka-over-red-lentil-pasta",
    "category": "lunchDinner",
    "description": "Spicy chicken alvodka over red lentil pasta",
    "davidRating": null,
    "lynnRating": null,
    "status": "favorite",
    "comments": "❤️",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-05-03",
    "timesOrdered": 2,
    "davidNote": "❤️",
    "lynnNote": "❤️"
  },
  {
    "id": "lunchDinner-lentil-and-ground-beef-soup",
    "category": "lunchDinner",
    "description": "Lentil and ground beef soup",
    "davidRating": null,
    "lynnRating": null,
    "status": "favorite",
    "comments": "❤️",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-03-15",
    "timesOrdered": 1,
    "davidNote": "❤️",
    "lynnNote": "❤️"
  },
  {
    "id": "lunchDinner-bbq-shredded-chicken-with-cabbage-slaw-and-tangy-citrus-farro",
    "category": "lunchDinner",
    "description": "Bbq Shredded chicken with cabbage slaw and tangy citrus farro",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "Yummy! Thought the slaw was too creamy.",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-01-19",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-greek-bison-patties-with-roasted-fingerling-potatoes-and-tzatziki",
    "category": "lunchDinner",
    "description": "Greek bison patties with roasted fingerling potatoes and tzatziki",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "❤️",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-05-03",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-lemon-grass-filet-bites-with-wasabi-mashed-potatoes-and-charred-broccolini",
    "category": "lunchDinner",
    "description": "Lemon grass filet bites with wasabi mashed potatoes and charred broccolini",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "Very good - David liked",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-01-19",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-chicken-satay-with-wasabi-edamame-mash-and-white-rice",
    "category": "lunchDinner",
    "description": "Chicken satay with wasabi edamame mash and white rice",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "❤️",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-05-24",
    "timesOrdered": 2,
    "davidNote": "",
    "lynnNote": "❤️"
  },
  {
    "id": "lunchDinner-chicken-pasta-salad-with-lentil-pasta",
    "category": "lunchDinner",
    "description": "Chicken pasta salad with lentil pasta",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "❤️",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-05-31",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-honey-lime-chicken-with-cabbage-slaw",
    "category": "lunchDinner",
    "description": "Honey lime chicken with cabbage slaw",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-07-12",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-chinese-chicken-salad-with-rice-noodles",
    "category": "lunchDinner",
    "description": "Chinese chicken salad with rice noodles",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "❤️",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-05-24",
    "timesOrdered": 2,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-pomegranate-braised-lamb-with-zucchini-and-pistachio-mint-rice",
    "category": "lunchDinner",
    "description": "Pomegranate braised lamb with zucchini and pistachio mint rice",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-lemon-broccoli-rabe-with-chicken-and-white-beans",
    "category": "lunchDinner",
    "description": "Lemon broccoli rabe with chicken and white beans",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-06-21",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-bison-stuffed-zucchini-boats-with-marinara-and-chickpeas",
    "category": "lunchDinner",
    "description": "Bison stuffed zucchini boats with marinara and chickpeas",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-07-26",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-korean-beef-or-bison-lettuce-cups-with-white-rice",
    "category": "lunchDinner",
    "description": "Korean beef or bison lettuce cups with white rice",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "❤️",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-07-12",
    "timesOrdered": 3,
    "davidNote": "",
    "lynnNote": "❤️"
  },
  {
    "id": "lunchDinner-garlic-butter-filet-bites-with-rosemary-potatoes-and-asparagus",
    "category": "lunchDinner",
    "description": "Garlic butter filet bites with rosemary potatoes and asparagus",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-miso-roasted-chicken-and-roasted-root-vegetables-melody",
    "category": "lunchDinner",
    "description": "Miso roasted chicken and roasted root vegetables melody",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-sweet-street-corn-chicken-bowls-with-quinoa",
    "category": "lunchDinner",
    "description": "Sweet street corn chicken bowls with white rice",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-07-26",
    "timesOrdered": 2,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-sheet-pan-gnocchi-gluten-freen-with-marinated-chicken-feta-and-vegetables",
    "category": "lunchDinner",
    "description": "Sheet pan gnocchi ( gluten freen ) with marinated chicken feta and vegetables",
    "davidRating": null,
    "lynnRating": null,
    "status": "favorite",
    "comments": "",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-02-15",
    "timesOrdered": 1,
    "davidNote": "❤️",
    "lynnNote": "❤️"
  },
  {
    "id": "lunchDinner-turkey-spinach-and-feta-patty-burger-bowl-with-jalapeno-yogurt-white-rice",
    "category": "lunchDinner",
    "description": "Turkey spinach and feta patty burger bowl with jalapeno yogurt white rice",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-02-02",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-honey-harissa-chicken-roasted-chicken-with-green-beans-and-chickpeas",
    "category": "lunchDinner",
    "description": "Honey harissa chicken roasted chicken with green beans and chickpeas",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-07-12",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-cajun-chicken-bake-with-white-beans",
    "category": "lunchDinner",
    "description": "Cajun chicken bake with white beans",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-garlic-and-pepper-steak-with-bone-broth-farro",
    "category": "lunchDinner",
    "description": "Garlic and pepper steak with bone broth farro",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-filet-ginger-sesame-beef-and-broccoli-with-white-rice",
    "category": "lunchDinner",
    "description": "Filet ginger sesame beef and broccoli with white rice",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-02-15",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-tarragon-apple-chicken-salad-with-sweet-potato-chips",
    "category": "lunchDinner",
    "description": "Tarragon apple chicken salad with sweet potato chips",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-mexican-ground-turkey-cauliflower-nachos",
    "category": "lunchDinner",
    "description": "Mexican ground turkey cauliflower nachos",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "❤️  Mix in half white rice",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-05-31",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-oven-roasted-chicken-with-romesco-roasted-potatoes-and-green-beans",
    "category": "lunchDinner",
    "description": "Oven roasted chicken with romesco roasted potatoes and green beans",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-cashew-alfredo-with-chicken-and-chickpeas-dairy-free-light-parmesan",
    "category": "lunchDinner",
    "description": "Cashew alfredo with chicken and chickpeas ( dairy free) light parmesan",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-miso-glazed-ginger-chicken-charred-broccolini-and-sweet-potato-mash",
    "category": "lunchDinner",
    "description": "Miso glazed ginger chicken charred broccolini and sweet potato mash",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-tika-marsala-roasted-chicken-roasted-carrots-and-white-rice",
    "category": "lunchDinner",
    "description": "Tika marsala roasted chicken roasted carrots and white rice",
    "davidRating": null,
    "lynnRating": null,
    "status": "favorite",
    "comments": "❤️",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-05-17",
    "timesOrdered": 2,
    "davidNote": "❤️",
    "lynnNote": "❤️"
  },
  {
    "id": "lunchDinner-grilled-chicken-and-veggies-with-lemongrass-sauce-vermicelli-noodles",
    "category": "lunchDinner",
    "description": "Grilled chicken and veggies with lemongrass sauce vermicelli noodles",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "❤️",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-04-19",
    "timesOrdered": 2,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-chicken-with-orange-caper-and-tarragon-sauce-baby-potato-asparagus",
    "category": "lunchDinner",
    "description": "Chicken with orange caper and tarragon sauce baby potato asparagus",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-07-26",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-thai-chicken-salad-rice-bowl",
    "category": "lunchDinner",
    "description": "Thai chicken salad rice bowl",
    "davidRating": null,
    "lynnRating": null,
    "status": "favorite",
    "comments": "❤️",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-07-26",
    "timesOrdered": 3,
    "davidNote": "❤️",
    "lynnNote": "❤️"
  },
  {
    "id": "lunchDinner-chicken-broccoli-cheese-american-mozerella-and-cauliflower-rice-bake",
    "category": "lunchDinner",
    "description": "Chicken broccoli cheese(American/mozerella) and cauliflower rice bake",
    "davidRating": null,
    "lynnRating": null,
    "status": "favorite",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "2026-05-17",
    "timesOrdered": 2,
    "davidNote": "❤️",
    "lynnNote": "❤️"
  },
  {
    "id": "lunchDinner-marinated-chicken-with-artichoke-potato-salad-lemon-and-capers",
    "category": "lunchDinner",
    "description": "Marinated chicken with artichoke potato salad lemon and capers",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-grilled-orange-and-ponzu-pork-tenderloin-the-roasted-cabbage",
    "category": "lunchDinner",
    "description": "Grilled orange and ponzu pork tenderloin the roasted cabbage",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-apricot-and-date-lamb-tagine-with-pistachio-rice",
    "category": "lunchDinner",
    "description": "Apricot and date lamb tagine with pistachio rice",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-ground-beef-sweet-potato-and-cauliflower-nachos",
    "category": "lunchDinner",
    "description": "Ground Beef sweet potato and cauliflower nachos",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-lemongrass-beef-cabbage-cups-white-rice",
    "category": "lunchDinner",
    "description": "Lemongrass beef cabbage cups white rice",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "David did not like the meat",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-03-22",
    "timesOrdered": 1,
    "davidNote": "No",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-sheet-pan-chicken-kebabs-w-bell-pepper-zucchini-herby-couscous",
    "category": "lunchDinner",
    "description": "Sheet pan chicken kebabs w bell pepper zucchini herby couscous",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-04-26",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-grilled-half-bison-half-beef-patties-grated-cucumber-zucchini-salad-sweet-potato-fries",
    "category": "lunchDinner",
    "description": "Grilled half bison half beef patties grated cucumber zucchini salad sweet potato fries",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-hoisin-baked-chicken-with-roasted-carrots-and-quinoa",
    "category": "lunchDinner",
    "description": "Hoisin baked chicken with roasted carrots and quinoa",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-marinated-chicken-with-lemon-caraway-roasted-brussel-sprouts",
    "category": "lunchDinner",
    "description": "Marinated chicken with lemon caraway roasted brussel sprouts",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-04-19",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-marinated-roasted-chicken-with-green-bean-and-mustard-potato-salad",
    "category": "lunchDinner",
    "description": "Marinated roasted chicken with green bean and mustard potato salad",
    "davidRating": null,
    "lynnRating": null,
    "status": "favorite",
    "comments": "❤️",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-05-17",
    "timesOrdered": 2,
    "davidNote": "❤️ ❤️",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-sheet-pan-chicken-fajitas-with-bell-peppers-and-cauliflower-rice",
    "category": "lowCalorie",
    "description": "Sheet pan chicken fajitas with bell peppers and cauliflower rice",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "David didn't like - too much pepper",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-03-01",
    "timesOrdered": 1,
    "davidNote": "No",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-lemon-pepper-chicken-roasted-broccolini-and-asparagus-and-sweet-potato",
    "category": "lowCalorie",
    "description": "Lemon pepper chicken roasted broccolini and asparagus and sweet potato",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "❤️ Great!",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-06-21",
    "timesOrdered": 4,
    "davidNote": "",
    "lynnNote": "❤️"
  },
  {
    "id": "lowCalorie-marinated-oven-roasted-chicken-breast-with-beet-white-bean-and-feta-salad",
    "category": "lowCalorie",
    "description": "Marinated oven roasted chicken breast with beet white bean and feta salad",
    "davidRating": null,
    "lynnRating": null,
    "status": "favorite",
    "comments": "❤️",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-06-07",
    "timesOrdered": 3,
    "davidNote": "❤️",
    "lynnNote": "❤️"
  },
  {
    "id": "lowCalorie-ground-bison-skillet-with-roasted-sweet-potatoes-corn-and-bell-peppers",
    "category": "lowCalorie",
    "description": "Ground bison skillet with roasted sweet potatoes corn and bell peppers",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-02-22",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-tahini-roasted-chicken-breast-with-citrus-roasted-cabbage-bell-peppers",
    "category": "lowCalorie",
    "description": "Tahini roasted chicken breast with citrus roasted cabbage bell peppers",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "❤️",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-05-24",
    "timesOrdered": 3,
    "davidNote": "",
    "lynnNote": "❤️"
  },
  {
    "id": "lowCalorie-moroccan-spiced-ck-or-lamb-w-roasted-carrots-beets-w-pistachio-cauliflower-rice",
    "category": "lowCalorie",
    "description": "Moroccan spiced ck or lamb w/ roasted carrots beets w pistachio cauliflower rice",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-bison-patties-with-sweet-potato-fries-and-cabbage-salad",
    "category": "lowCalorie",
    "description": "Bison patties with sweet potato fries and cabbage salad",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-02-15",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-bang-bang-chicken-with-broccolini-and-cauliflower-rice",
    "category": "lowCalorie",
    "description": "Bang bang chicken with broccolini and cauliflower rice",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "❤️",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-02-02",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": "❤️"
  },
  {
    "id": "lowCalorie-lemongrass-and-coconut-beef-stew-with-seasonal-veg-and-squash",
    "category": "lowCalorie",
    "description": "Lemongrass and coconut beef stew with seasonal veg and squash",
    "davidRating": null,
    "lynnRating": null,
    "status": "favorite",
    "comments": "❤️",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-07-12",
    "timesOrdered": 4,
    "davidNote": "❤️",
    "lynnNote": "❤️"
  },
  {
    "id": "lowCalorie-grilled-chicken-with-pineapple-salsa-garlic-pepper-roasted-vegetables",
    "category": "lowCalorie",
    "description": "Grilled chicken with pineapple salsa garlic pepper roasted vegetables",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-02-15",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-shwarama-spiced-chicken-with-cauliflower-tabulieh",
    "category": "lowCalorie",
    "description": "Shwarama spiced chicken with cauliflower tabulieh",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-02-22",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-garlic-and-lemon-chicken-with-chickpeas-israeli-salad",
    "category": "lowCalorie",
    "description": "Garlic and lemon chicken with chickpeas israeli salad",
    "davidRating": null,
    "lynnRating": null,
    "status": "favorite",
    "comments": "❤️- great for summer (I ate it cold)",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-06-14",
    "timesOrdered": 2,
    "davidNote": "❤️",
    "lynnNote": "❤️"
  },
  {
    "id": "lowCalorie-sweet-potato-and-ground-chicken-turkey-chili",
    "category": "lowCalorie",
    "description": "Sweet potato and ground chicken/turkey chili",
    "davidRating": null,
    "lynnRating": null,
    "status": "favorite",
    "comments": "❤️",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-05-10",
    "timesOrdered": 3,
    "davidNote": "❤️",
    "lynnNote": "❤️ ❤️"
  },
  {
    "id": "lowCalorie-thai-beef-cabbage-salad",
    "category": "lowCalorie",
    "description": "Thai beef cabbage salad",
    "davidRating": null,
    "lynnRating": null,
    "status": "favorite",
    "comments": "❤️ ❤️  Loved the dressing",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-05-31",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-chicken-cabbage-and-beet-soup",
    "category": "lowCalorie",
    "description": "Chicken cabbage and beet soup",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "❤️ ❤️",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-06-21",
    "timesOrdered": 2,
    "davidNote": "",
    "lynnNote": "❤️"
  },
  {
    "id": "lowCalorie-adobo-grilled-chicken-with-cumin-black-beans-cabbage-cilantro-salad",
    "category": "lowCalorie",
    "description": "Adobo grilled chicken with cumin black beans cabbage cilantro salad",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "Lynn ❤️",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-05-03",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-rosemary-grilled-pork-tenderloin-with-grilled-veggies-lemon-white-beans",
    "category": "lowCalorie",
    "description": "Rosemary Grilled pork tenderloin with grilled veggies lemon white beans",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-lentils-and-ground-beef-harissa-cauliflower-dates-bowl",
    "category": "lowCalorie",
    "description": "Lentils and ground beef harissa cauliflower dates bowl",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-grilled-chicken-with-green-goddess-cabbage-salad",
    "category": "lowCalorie",
    "description": "Grilled chicken with green goddess cabbage salad",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "❤️",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-04-26",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": "❤️"
  },
  {
    "id": "lowCalorie-grilled-bratwurst-with-apple-fennel-cabbage-salad",
    "category": "lowCalorie",
    "description": "Grilled bratwurst with apple fennel cabbage salad",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "David wants less processed meats, maybe shredding chicken",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-06-07",
    "timesOrdered": 2,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-cilantro-lime-baked-chicken-with-roasted-corn-white-beans-salad",
    "category": "lowCalorie",
    "description": "Cilantro lime baked chicken with roasted corn white beans salad",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "David thinks chicken is tough",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-04-12",
    "timesOrdered": 1,
    "davidNote": "David didn't like the chicken",
    "lynnNote": "Ok"
  },
  {
    "id": "lowCalorie-bison-skillet-with-apple-butter-roasted-carrots-white-rice",
    "category": "lowCalorie",
    "description": "Bison skillet with apple butter roasted carrots white rice",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "❤️",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-03-29",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-tendrion-with-shisito-pepper-salsa-asparagus-and-baby-potatoes",
    "category": "lowCalorie",
    "description": "Tendrion with shisito pepper salsa asparagus and baby potatoes",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": "❤️"
  },
  {
    "id": "lowCalorie-chicken-fennel-and-cabbage-stew",
    "category": "lowCalorie",
    "description": "Chicken fennel and cabbage stew",
    "davidRating": null,
    "lynnRating": null,
    "status": "favorite",
    "comments": "❤️",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-06-14",
    "timesOrdered": 3,
    "davidNote": "",
    "lynnNote": "❤️ ❤️"
  },
  {
    "id": "lowCalorie-marinated-chicken-with-orange-beet-and-carrot-salad",
    "category": "lowCalorie",
    "description": "Marinated chicken with orange beet and carrot salad",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "❤️",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-05-31",
    "timesOrdered": 2,
    "davidNote": "",
    "lynnNote": "❤️"
  },
  {
    "id": "lowCalorie-grilled-chicken-roasted-sweet-potato-apple-cabbage-salad-with-hummus-dressing",
    "category": "lowCalorie",
    "description": "Grilled chicken roasted sweet potato apple cabbage salad with hummus dressing",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-04-19",
    "timesOrdered": 2,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-ginger-and-thai-chili-chicken-skewers-w-peanut-dressing-cabbage-salad",
    "category": "lowCalorie",
    "description": "Ginger and thai chili chicken skewers w peanut dressing cabbage salad",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-08-02",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-tuscan-marinated-chicken-w-herby-asparagus-and-pea-feta-potato-salad",
    "category": "lowCalorie",
    "description": "Tuscan marinated chicken w herby asparagus and pea feta potato salad",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-marinated-grilled-chicken-with-beet-and-apple-salad",
    "category": "lowCalorie",
    "description": "Marinated grilled chicken with beet and apple salad",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-baked-red-curry-chicken-cabbage-cups-with-white-rice",
    "category": "lowCalorie",
    "description": "Baked red curry chicken cabbage cups with white rice",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-marinated-grilled-chicken-with-beet-farro-salad-spiced-ginger-lime-dressing",
    "category": "lowCalorie",
    "description": "Marinated Grilled chicken with beet farro salad spiced ginger lime dressing",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-08-02",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-mustard-roasted-chicken-with-pea-preserved-lemon-and-mint-mash",
    "category": "lowCalorie",
    "description": "Mustard roasted chicken with pea preserved lemon and mint mash",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-miso-and-sesame-roasted-chicken-w-ginger-and-garlic-root-vegetables",
    "category": "lowCalorie",
    "description": "Miso and sesame roasted chicken w/ ginger and garlic root vegetables",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-grilled-chicken-with-curry-brown-rice-noodle-salad",
    "category": "lowCalorie",
    "description": "Grilled chicken with curry brown rice noodle salad",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-cabbage-cob-salad-with-grilled-chicken",
    "category": "lowCalorie",
    "description": "Cabbage cob salad with grilled chicken",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-ground-bison-or-turkey-stuffed-bell-peppers",
    "category": "lowCalorie",
    "description": "Ground bison or turkey stuffed bell peppers",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-roasted-root-vegetable-and-farro-salad-with-oregano-caper-vinaigrette-vegan",
    "category": "lowCalorie",
    "description": "Roasted root vegetable and farro salad with oregano caper vinaigrette (vegan)",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-red-wine-braised-pot-roast-with-horseradish-parsnip-and-cauliflower-mash",
    "category": "lowCalorie",
    "description": "Red wine braised pot roast with horseradish parsnip and cauliflower mash",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-italian-ground-chicken-and-lentil-stew",
    "category": "lowCalorie",
    "description": "Italian ground chicken and lentil stew",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-bison-beef-patties-with-balsamic-grilled-corn-beet-and-mint-salad",
    "category": "lowCalorie",
    "description": "Bison/beef patties with balsamic grilled corn beet and mint salad",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-charred-green-onion-turkey-patties-raw-beet-and-walnut-salad-with-orange-blossom-dressing",
    "category": "lowCalorie",
    "description": "Charred green onion turkey patties raw beet and walnut salad with orange blossom dressing",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-mustard-filets-bites-with-horseradish-cauliflower-and-parsnip-puree",
    "category": "lowCalorie",
    "description": "Mustard filets bites with horseradish cauliflower and parsnip puree",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-07-19",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-herbed-baked-chicken-with-lentil-carrot-dill-and-feta-salad",
    "category": "lowCalorie",
    "description": "Herbed baked chicken with lentil carrot dill and feta salad",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-balsamic-grilled-chicken-with-beet-and-pineapple-salad",
    "category": "lowCalorie",
    "description": "Balsamic Grilled chicken with beet and pineapple salad",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-marinated-grilled-chicken-and-veggies-over-farro-with-basil-vinaigrette",
    "category": "lowCalorie",
    "description": "Marinated grilled chicken and veggies over farro with basil vinaigrette",
    "davidRating": null,
    "lynnRating": null,
    "status": "ordered",
    "comments": "",
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "2026-07-19",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-marinated-grilled-chicken-with-blisters-green-beans-fenugreek-chipotle-tomato-sauce",
    "category": "lowCalorie",
    "description": "Marinated Grilled chicken with blisters green beans fenugreek chipotle tomato sauce",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-asian-marinated-grilled-chicken-rice-salad",
    "category": "lowCalorie",
    "description": "Asian marinated grilled chicken rice salad",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-oven-roasted-chicken-w-root-vegetables-with-lemon-caraway-and-pinenuts-parsley",
    "category": "lowCalorie",
    "description": "Oven roasted chicken w/ root vegetables with lemon caraway and pinenuts/ parsley",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-balsamic-marinated-chicken-cabbage-farro-salad-strawberry-jalapeno-dressing",
    "category": "lowCalorie",
    "description": "Balsamic marinated chicken cabbage farro salad strawberry jalapeno dressing",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-turkey-white-bean-and-pumpkin-chilli",
    "category": "lowCalorie",
    "description": "Turkey white bean and pumpkin chilli",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-lemon-grass-chicken-salad-with-cabbage-and-brown-rice-noodles",
    "category": "lowCalorie",
    "description": "Lemon grass chicken salad with cabbage and brown rice noodles",
    "davidRating": null,
    "lynnRating": null,
    "status": "notOrdered",
    "comments": "",
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  }
]
