export type MealCategory = 'breakfast' | 'lunchDinner' | 'lowCalorie'

export type Meal = {
  id: string
  category: MealCategory
  description: string
  rating: number | null
  recommendedBecause: string
  lastOrderedDate: string
  timesOrdered: number
  davidNote?: string
  lynnNote?: string
}

export const meals: Meal[] = [
  {
    "id": "breakfast-herbed-goat-cheese-frittata-or-ricotta-and-sweet-potato-frittata",
    "category": "breakfast",
    "description": "Herbed goat cheese frittata or ricotta and sweet potato frittata",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-hard-boiled-eggs-with-jalapeno-chickpea-flour-pancakes",
    "category": "breakfast",
    "description": "Hard boiled eggs with jalapeno chickpea flour pancakes",
    "rating": null,
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-white-bean-and-egg-bake-with-herbs",
    "category": "breakfast",
    "description": "White bean and egg bake with herbs",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-chickpea-flour-pancakes-with-lemon-hummus-cottage-and-cucumbers",
    "category": "breakfast",
    "description": "Chickpea flour pancakes with lemon hummus cottage and cucumbers",
    "rating": null,
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-hard-boiled-eggs-turkey-bacon-or-chicken-sausage-and-cucumber-tomato-platter",
    "category": "breakfast",
    "description": "Hard boiled eggs/ turkey bacon or chicken sausage and cucumber tomato platter",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-avocado-egg-and-brown-rice-bowls",
    "category": "breakfast",
    "description": "Avocado egg and brown rice bowls",
    "rating": null,
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-lemon-and-banana-protein-pancake-w-side-of-greek-yogurt-no-flour",
    "category": "breakfast",
    "description": "Lemon and banana protein pancake w side of greek yogurt ( no flour)",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "Not a fave",
    "lynnNote": "Not a fave"
  },
  {
    "id": "breakfast-egg-white-and-cheddar-chicken-sausage-frittata",
    "category": "breakfast",
    "description": "Egg white and cheddar chicken sausage frittata",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-tiramisu-protein-overnight-oats",
    "category": "breakfast",
    "description": "Tiramisu protein overnight oats",
    "rating": null,
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-sweet-potato-hash-and-fried-eggs-with-avocado-drizzle",
    "category": "breakfast",
    "description": "Sweet potato hash and fried eggs with avocado drizzle",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-mediterranean-feta-bake-eggs",
    "category": "breakfast",
    "description": "Mediterranean feta bake eggs",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": "Pretty good - like the carrots"
  },
  {
    "id": "breakfast-cottage-cheese-scrambled-eggs-avocado-and-chicken-sausage-links",
    "category": "breakfast",
    "description": "Cottage cheese scrambled eggs avocado and chicken sausage links",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": "❤️"
  },
  {
    "id": "breakfast-gluten-free-open-face-quesadilla-spinach-egg-and-cheddar",
    "category": "breakfast",
    "description": "Gluten free open face quesadilla spinach egg and cheddar",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-sweet-potato-toast-with-harissa-chickpeas-or-peanut-butter-and-fresh-fruit-compote",
    "category": "breakfast",
    "description": "Sweet potato toast with harissa chickpeas or peanut butter and fresh fruit compote",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-turmeric-asparagus-pistachio-savory-overnight-oats-with-egg",
    "category": "breakfast",
    "description": "Turmeric asparagus pistachio savory overnight oats ( with egg)",
    "rating": null,
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-greek-yogurt-bowls-fresh-fruit-and-nuts-with-light-granola",
    "category": "breakfast",
    "description": "Greek yogurt bowls fresh fruit and nuts with light granola",
    "rating": null,
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-chicken-sausage-sweet-potato-casserole",
    "category": "breakfast",
    "description": "Chicken sausage sweet potato casserole",
    "rating": null,
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-spinach-chickpeas-and-feta-bake-with-side-of-turkey-bacon",
    "category": "breakfast",
    "description": "Spinach chickpeas and feta bake with ( side of turkey bacon)",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "Too many beans",
    "lynnNote": "❤️"
  },
  {
    "id": "breakfast-scrambled-eggs-with-artichokes-capers-rosemary-side-or-chicken-sausage",
    "category": "breakfast",
    "description": "Scrambled eggs with artichokes capers rosemary ( side or chicken sausage)",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "More egg",
    "lynnNote": "More egg"
  },
  {
    "id": "breakfast-pistachio-overnight-protein-oats-pistachio-milk-crushed-pistachios-make-less-dry",
    "category": "breakfast",
    "description": "Pistachio overnight protein oats ( pistachio milk crushed Pistachios make less dry)",
    "rating": null,
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-fresh-fruit-oatmeal-bake-side-of-turkey-bacon",
    "category": "breakfast",
    "description": "Fresh fruit oatmeal bake ( side of turkey bacon)",
    "rating": null,
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-lemon-berry-ricotta-and-cottage-cheese-bowls-with-granola",
    "category": "breakfast",
    "description": "Lemon berry ricotta and cottage cheese bowls with granola",
    "rating": null,
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-everything-bagel-cottage-cheese-bowls-turkey-bacon-eggs-cucumber-radish",
    "category": "breakfast",
    "description": "Everything bagel cottage cheese bowls ( turkey bacon eggs cucumber radish)",
    "rating": null,
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-hashbrown-quiche-veggie-and-turkey-bacon-or-chicken-sausage-cups",
    "category": "breakfast",
    "description": "Hashbrown quiche veggie and turkey bacon or chicken sausage cups",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-open-face-quesadillas-with-egg-sausage-and-american-cheese-corn-tortillas",
    "category": "breakfast",
    "description": "Open face quesadillas with egg sausage and american cheese ( corn tortillas)",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-egg-and-banana-pancakes-with-fresh-fruit-chicken-sausage",
    "category": "breakfast",
    "description": "Egg and banana pancakes with fresh fruit chicken sausage",
    "rating": null,
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "breakfast-spinach-feta-scrambled-egg-pitas",
    "category": "breakfast",
    "description": "Spinach feta scrambled egg pitas",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-moroccan-spiced-chicken-with-quinoa-and-green-beans",
    "category": "lunchDinner",
    "description": "Moroccan spiced chicken with quinoa and green beans",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": "Good"
  },
  {
    "id": "lunchDinner-mediterranean-turkey-chicken-quinoa-meatballs-with-tahini-roasted-carrots",
    "category": "lunchDinner",
    "description": "Mediterranean turkey & chicken quinoa meatballs with tahini roasted carrots",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-moroccan-lentil-bowls",
    "category": "lunchDinner",
    "description": "Moroccan lentil bowls",
    "rating": null,
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-filet-with-chimichurri-fingerling-potatoes-green-cabbage-salad",
    "category": "lunchDinner",
    "description": "Filet with chimichurri fingerling potatoes green cabbage salad",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-beef-harissa-meatballs-with-roasted-chickpeas-and-veggies",
    "category": "lunchDinner",
    "description": "Beef harissa meatballs with roasted chickpeas and veggies",
    "rating": null,
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-turkey-beef-meatloaf-w-fennel-bbq-sauce-mashed-sweet-potato-and-broccolini",
    "category": "lunchDinner",
    "description": "Turkey/ beef meatloaf w fennel bbq sauce mashed sweet potato and broccolini",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "❤️",
    "lynnNote": "❤️"
  },
  {
    "id": "lunchDinner-roasted-balsamic-chicken-with-white-rice-and-roasted-root-vegetables",
    "category": "lunchDinner",
    "description": "Roasted balsamic chicken with white rice and roasted root vegetables",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-italian-zucchini-boats-over-a-bed-of-quinoa",
    "category": "lunchDinner",
    "description": "Italian zucchini boats over a bed of quinoa",
    "rating": null,
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-lentil-zucchini-and-mint-salad",
    "category": "lunchDinner",
    "description": "Lentil zucchini and mint salad",
    "rating": null,
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-thai-turkey-and-chicken-meatballs-with-cauliflower-stir-fry-rice",
    "category": "lunchDinner",
    "description": "Thai turkey and chicken meatballs with cauliflower stir fry rice",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-lamb-chops-with-apricot-chutney-mint-sweet-pea-mash-quinoa-with-pistachios",
    "category": "lunchDinner",
    "description": "Lamb chops with apricot chutney mint sweet pea mash quinoa with pistachios",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "sub in something besides quinoa",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-filet-with-horseradish-sauce-green-bean-salad-and-sweet-potato-medallions",
    "category": "lunchDinner",
    "description": "Filet with horseradish sauce green bean salad and sweet potato medallions",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-oven-roasted-chicken-with-chili-spiced-green-beans-and-turmeric-rice",
    "category": "lunchDinner",
    "description": "Oven roasted chicken with chili spiced green beans and turmeric rice",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-marinated-oven-roasted-chicken-breast-with-beet-white-bean-and-feta-salad",
    "category": "lunchDinner",
    "description": "Marinated oven roasted chicken breast with beet white bean and feta salad",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "w beets but sub in something besides quinoa",
    "lynnNote": "❤️"
  },
  {
    "id": "lunchDinner-chicken-shawarma-skewers-with-spiced-basmati-rice",
    "category": "lunchDinner",
    "description": "Chicken shawarma skewers with spiced basmati rice",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-ground-chicken-lettuce-wraps-with-basmati-rice",
    "category": "lunchDinner",
    "description": "Ground chicken lettuce wraps with basmati rice",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "❤️",
    "lynnNote": "❤️"
  },
  {
    "id": "lunchDinner-roast-chicken-fall-harvest-bowl-with-hummus-and-quinoa",
    "category": "lunchDinner",
    "description": "Roast chicken fall harvest bowl with hummus and quinoa",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-buffalo-chicken-with-cauliflower-florets-and-quinoa",
    "category": "lunchDinner",
    "description": "Buffalo chicken with cauliflower florets and quinoa",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-tuscan-chicken-white-bean-and-spinach-stew",
    "category": "lunchDinner",
    "description": "Tuscan chicken white bean and spinach stew",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": "❤️"
  },
  {
    "id": "lunchDinner-shredded-green-chile-chicken-with-cabbage-and-black-beans",
    "category": "lunchDinner",
    "description": "Shredded green chile chicken with cabbage and black beans",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-chicken-piccata-with-asparagus-and-baby-potatoes",
    "category": "lunchDinner",
    "description": "Chicken piccata with asparagus and baby potatoes",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "❤️",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-chicken-turkey-ragu-marina-with-spaghetti-squash-pasta",
    "category": "lunchDinner",
    "description": "Chicken Turkey ragu marina with spaghetti squash pasta",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": "❤️"
  },
  {
    "id": "lunchDinner-thai-green-curry-chicken-with-bell-peppers-with-basmati-rice",
    "category": "lunchDinner",
    "description": "Thai green curry chicken with bell peppers with basmati rice",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": "❤️"
  },
  {
    "id": "lunchDinner-lemongrass-black-pepper-filet-bites-with-asparagus-and-white-rice",
    "category": "lunchDinner",
    "description": "Lemongrass black pepper filet bites with asparagus and white rice",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-chicken-salad-w-smashed-cucumbers-chili-crisp-and-jalapeno-hummus",
    "category": "lunchDinner",
    "description": "Chicken salad w smashed cucumbers chili crisp and jalapeno hummus",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "❤️",
    "lynnNote": "❤️"
  },
  {
    "id": "lunchDinner-chicken-laab-with-white-rice",
    "category": "lunchDinner",
    "description": "Chicken Laab with white rice",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-braised-chicken-and-cabbage-with-sumac-and-lime-white-rice",
    "category": "lunchDinner",
    "description": "Braised chicken and cabbage with sumac and lime white rice",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-lemon-pepper-chicken-greek-goddess-bowls-with-white-beans",
    "category": "lunchDinner",
    "description": "Lemon pepper chicken greek goddess bowls with white beans",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "❤️",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-filet-jalapeno-cilantro-yogurt-sauce-and-black-bean-and-corn-salad",
    "category": "lunchDinner",
    "description": "Filet jalapeno cilantro yogurt sauce and black bean and corn salad",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-ground-bison-sloppy-joe-stuffed-sweet-potatoes",
    "category": "lunchDinner",
    "description": "Ground bison sloppy joe stuffed sweet potatoes",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": "❤️"
  },
  {
    "id": "lunchDinner-coconut-chicken-with-peanut-salsa-rice-noodles",
    "category": "lunchDinner",
    "description": "Coconut chicken with peanut salsa rice noodles",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": "❤️"
  },
  {
    "id": "lunchDinner-spicy-chicken-alvodka-over-red-lentil-pasta",
    "category": "lunchDinner",
    "description": "Spicy chicken alvodka over red lentil pasta",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "❤️",
    "lynnNote": "❤️"
  },
  {
    "id": "lunchDinner-lentil-and-ground-beef-soup",
    "category": "lunchDinner",
    "description": "Lentil and ground beef soup",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "❤️",
    "lynnNote": "❤️"
  },
  {
    "id": "lunchDinner-bbq-shredded-chicken-with-cabbage-slaw-and-tangy-citrus-farro",
    "category": "lunchDinner",
    "description": "Bbq Shredded chicken with cabbage slaw and tangy citrus farro",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-greek-bison-patties-with-roasted-fingerling-potatoes-and-tzatziki",
    "category": "lunchDinner",
    "description": "Greek bison patties with roasted fingerling potatoes and tzatziki",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-lemon-grass-filet-bites-with-wasabi-mashed-potatoes-and-charred-broccolini",
    "category": "lunchDinner",
    "description": "Lemon grass filet bites with wasabi mashed potatoes and charred broccolini",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-chicken-satay-with-wasabi-edamame-mash-and-white-rice",
    "category": "lunchDinner",
    "description": "Chicken satay with wasabi edamame mash and white rice",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": "❤️"
  },
  {
    "id": "lunchDinner-chicken-pasta-salad-with-lentil-pasta",
    "category": "lunchDinner",
    "description": "Chicken pasta salad with lentil pasta",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-honey-lime-chicken-with-cabbage-slaw",
    "category": "lunchDinner",
    "description": "Honey lime chicken with cabbage slaw",
    "rating": null,
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-chinese-chicken-salad-with-rice-noodles",
    "category": "lunchDinner",
    "description": "Chinese chicken salad with rice noodles",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-pomegranate-braised-lamb-with-zucchini-and-pistachio-mint-rice",
    "category": "lunchDinner",
    "description": "Pomegranate braised lamb with zucchini and pistachio mint rice",
    "rating": null,
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-lemon-broccoli-rabe-with-chicken-and-white-beans",
    "category": "lunchDinner",
    "description": "Lemon broccoli rabe with chicken and white beans",
    "rating": null,
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-bison-stuffed-zucchini-boats-with-marinara-and-chickpeas",
    "category": "lunchDinner",
    "description": "Bison stuffed zucchini boats with marinara and chickpeas",
    "rating": null,
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-korean-beef-or-bison-lettuce-cups-with-white-rice",
    "category": "lunchDinner",
    "description": "Korean beef or bison lettuce cups with white rice",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": "❤️"
  },
  {
    "id": "lunchDinner-garlic-butter-filet-bites-with-rosemary-potatoes-and-asparagus",
    "category": "lunchDinner",
    "description": "Garlic butter filet bites with rosemary potatoes and asparagus",
    "rating": null,
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-miso-roasted-chicken-and-roasted-root-vegetables-melody",
    "category": "lunchDinner",
    "description": "Miso roasted chicken and roasted root vegetables melody",
    "rating": null,
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-sweet-street-corn-chicken-bowls-with-quinoa",
    "category": "lunchDinner",
    "description": "Sweet street corn chicken bowls with quinoa",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-sheet-pan-gnocchi-gluten-freen-with-marinated-chicken-feta-and-vegetables",
    "category": "lunchDinner",
    "description": "Sheet pan gnocchi ( gluten freen ) with marinated chicken feta and vegetables",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "❤️",
    "lynnNote": "❤️"
  },
  {
    "id": "lunchDinner-turkey-spinach-and-feta-patty-burger-bowl-with-jalapeno-yogurt-white-rice",
    "category": "lunchDinner",
    "description": "Turkey spinach and feta patty burger bowl with jalapeno yogurt white rice",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-honey-harissa-chicken-roasted-chicken-with-green-beans-and-chickpeas",
    "category": "lunchDinner",
    "description": "Honey harissa chicken roasted chicken with green beans and chickpeas",
    "rating": null,
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-cajun-chicken-bake-with-white-beans",
    "category": "lunchDinner",
    "description": "Cajun chicken bake with white beans",
    "rating": null,
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-garlic-and-pepper-steak-with-bone-broth-farro",
    "category": "lunchDinner",
    "description": "Garlic and pepper steak with bone broth farro",
    "rating": null,
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-filet-ginger-sesame-beef-and-broccoli-with-white-rice",
    "category": "lunchDinner",
    "description": "Filet ginger sesame beef and broccoli with white rice",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-tarragon-apple-chicken-salad-with-sweet-potato-chips",
    "category": "lunchDinner",
    "description": "Tarragon apple chicken salad with sweet potato chips",
    "rating": null,
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-mexican-ground-turkey-cauliflower-nachos",
    "category": "lunchDinner",
    "description": "Mexican ground turkey cauliflower nachos",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-oven-roasted-chicken-with-romesco-roasted-potatoes-and-green-beans",
    "category": "lunchDinner",
    "description": "Oven roasted chicken with romesco roasted potatoes and green beans",
    "rating": null,
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-cashew-alfredo-with-chicken-and-chickpeas-dairy-free-light-parmesan",
    "category": "lunchDinner",
    "description": "Cashew alfredo with chicken and chickpeas ( dairy free) light parmesan",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-miso-glazed-ginger-chicken-charred-broccolini-and-sweet-potato-mash",
    "category": "lunchDinner",
    "description": "Miso glazed ginger chicken charred broccolini and sweet potato mash",
    "rating": null,
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-tika-marsala-roasted-chicken-roasted-carrots-and-white-rice",
    "category": "lunchDinner",
    "description": "Tika marsala roasted chicken roasted carrots and white rice",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "❤️",
    "lynnNote": "❤️"
  },
  {
    "id": "lunchDinner-grilled-chicken-and-veggies-with-lemongrass-sauce-vermicelli-noodles",
    "category": "lunchDinner",
    "description": "Grilled chicken and veggies with lemongrass sauce vermicelli noodles",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-chicken-with-orange-caper-and-tarragon-sauce-baby-potato-asparagus",
    "category": "lunchDinner",
    "description": "Chicken with orange caper and tarragon sauce baby potato asparagus",
    "rating": null,
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-thai-chicken-salad-rice-bowl",
    "category": "lunchDinner",
    "description": "Thai chicken salad rice bowl",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "❤️",
    "lynnNote": "❤️"
  },
  {
    "id": "lunchDinner-chicken-broccoli-cheese-american-mozerella-and-cauliflower-rice-bake",
    "category": "lunchDinner",
    "description": "Chicken broccoli cheese( american/mozerella) and cauliflower rice bake",
    "rating": null,
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "❤️",
    "lynnNote": "❤️"
  },
  {
    "id": "lunchDinner-marinated-chicken-with-artichoke-potato-salad-lemon-and-capers",
    "category": "lunchDinner",
    "description": "Marinated chicken with artichoke potato salad lemon and capers",
    "rating": null,
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-grilled-orange-and-ponzu-pork-tenderloin-the-roasted-cabbage",
    "category": "lunchDinner",
    "description": "Grilled orange and ponzu pork tenderloin the roasted cabbage",
    "rating": null,
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-apricot-and-date-lamb-tagine-with-pistachio-rice",
    "category": "lunchDinner",
    "description": "Apricot and date lamb tagine with pistachio rice",
    "rating": null,
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-ground-beef-sweet-potato-and-cauliflower-nachos",
    "category": "lunchDinner",
    "description": "Ground Beef sweet potato and cauliflower nachos",
    "rating": null,
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-lemongrass-beef-cabbage-cups-white-rice",
    "category": "lunchDinner",
    "description": "Lemongrass beef cabbage cups white rice",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "No",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-sheet-pan-chicken-kebabs-w-bell-pepper-zucchini-herby-couscous",
    "category": "lunchDinner",
    "description": "Sheet pan chicken kebabs w bell pepper zucchini herby couscous",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-grilled-half-bison-half-beef-patties-grated-cucumber-zucchini-salad-sweet-potato-fries",
    "category": "lunchDinner",
    "description": "Grilled half bison half beef patties grated cucumber zucchini salad sweet potato fries",
    "rating": null,
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-hoisin-baked-chicken-with-roasted-carrots-and-quinoa",
    "category": "lunchDinner",
    "description": "Hoisin baked chicken with roasted carrots and quinoa",
    "rating": null,
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-marinated-chicken-with-lemon-caraway-roasted-brussel-sprouts",
    "category": "lunchDinner",
    "description": "Marinated chicken with lemon caraway roasted brussel sprouts",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lunchDinner-marinated-roasted-chicken-with-green-bean-and-mustard-potato-salad",
    "category": "lunchDinner",
    "description": "Marinated roasted chicken with green bean and mustard potato salad",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "❤️ ❤️",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-sheet-pan-chicken-fajitas-with-bell-peppers-and-cauliflower-rice",
    "category": "lowCalorie",
    "description": "Sheet pan chicken fajitas with bell peppers and cauliflower rice",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "No",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-lemon-pepper-chicken-roasted-broccolini-and-asparagus-and-sweet-potato",
    "category": "lowCalorie",
    "description": "Lemon pepper chicken roasted broccolini and asparagus and sweet potato",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": "❤️"
  },
  {
    "id": "lowCalorie-marinated-oven-roasted-chicken-breast-with-beet-white-bean-and-feta-salad",
    "category": "lowCalorie",
    "description": "Marinated oven roasted chicken breast with beet white bean and feta salad",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "❤️",
    "lynnNote": "❤️"
  },
  {
    "id": "lowCalorie-ground-bison-skillet-with-roasted-sweet-potatoes-corn-and-bell-peppers",
    "category": "lowCalorie",
    "description": "Ground bison skillet with roasted sweet potatoes corn and bell peppers",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-tahini-roasted-chicken-breast-with-citrus-roasted-cabbage-bell-peppers",
    "category": "lowCalorie",
    "description": "Tahini roasted chicken breast with citrus roasted cabbage bell peppers",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": "❤️"
  },
  {
    "id": "lowCalorie-moroccan-spiced-ck-or-lamb-w-roasted-carrots-beets-w-pistachio-cauliflower-rice",
    "category": "lowCalorie",
    "description": "Moroccan spiced ck or lamb w/ roasted carrots beets w pistachio cauliflower rice",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-bison-patties-with-sweet-potato-fries-and-cabbage-salad",
    "category": "lowCalorie",
    "description": "Bison patties with sweet potato fries and cabbage salad",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-bang-bang-chicken-with-broccolini-and-cauliflower-rice",
    "category": "lowCalorie",
    "description": "Bang bang chicken with broccolini and cauliflower rice",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": "❤️"
  },
  {
    "id": "lowCalorie-lemongrass-and-coconut-beef-stew-with-seasonal-veg-and-squash",
    "category": "lowCalorie",
    "description": "Lemongrass and coconut beef stew with seasonal veg and squash",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "❤️",
    "lynnNote": "❤️"
  },
  {
    "id": "lowCalorie-grilled-chicken-with-pineapple-salsa-garlic-pepper-roasted-vegetables",
    "category": "lowCalorie",
    "description": "Grilled chicken with pineapple salsa garlic pepper roasted vegetables",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-shwarama-spiced-chicken-with-cauliflower-tabulieh",
    "category": "lowCalorie",
    "description": "Shwarama spiced chicken with cauliflower tabulieh",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-garlic-and-lemon-chicken-with-chickpeas-israeli-salad",
    "category": "lowCalorie",
    "description": "Garlic and lemon chicken with chickpeas israeli salad",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "❤️",
    "lynnNote": "❤️"
  },
  {
    "id": "lowCalorie-sweet-potato-and-ground-chicken-turkey-chili",
    "category": "lowCalorie",
    "description": "Sweet potato and ground chicken/turkey chili",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "❤️",
    "lynnNote": "❤️ ❤️"
  },
  {
    "id": "lowCalorie-thai-beef-cabbage-salad",
    "category": "lowCalorie",
    "description": "Thai beef cabbage salad",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-chicken-cabbage-and-beet-soup",
    "category": "lowCalorie",
    "description": "Chicken cabbage and beet soup",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": "❤️"
  },
  {
    "id": "lowCalorie-adobo-grilled-chicken-with-cumin-black-beans-cabbage-cilantro-salad",
    "category": "lowCalorie",
    "description": "Adobo grilled chicken with cumin black beans cabbage cilantro salad",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-rosemary-grilled-pork-tenderloin-with-grilled-veggies-lemon-white-beans",
    "category": "lowCalorie",
    "description": "Rosemary Grilled pork tenderloin with grilled veggies lemon white beans",
    "rating": null,
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-lentils-and-ground-beef-harissa-cauliflower-dates-bowl",
    "category": "lowCalorie",
    "description": "Lentils and ground beef harissa cauliflower dates bowl",
    "rating": null,
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-grilled-chicken-with-green-goddess-cabbage-salad",
    "category": "lowCalorie",
    "description": "Grilled chicken with green goddess cabbage salad",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": "❤️"
  },
  {
    "id": "lowCalorie-grilled-bratwurst-with-apple-fennel-cabbage-salad",
    "category": "lowCalorie",
    "description": "Grilled bratwurst with apple fennel cabbage salad",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-cilantro-lime-baked-chicken-with-roasted-corn-white-beans-salad",
    "category": "lowCalorie",
    "description": "Cilantro lime baked chicken with roasted corn white beans salad",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "David didn't like the chicken",
    "lynnNote": "Ok"
  },
  {
    "id": "lowCalorie-bison-skillet-with-apple-butter-roasted-carrots-white-rice",
    "category": "lowCalorie",
    "description": "Bison skillet with apple butter roasted carrots white rice",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  },
  {
    "id": "lowCalorie-tendrion-with-shisito-pepper-salsa-asparagus-and-baby-potatoes",
    "category": "lowCalorie",
    "description": "Tendrion with shisito pepper salsa asparagus and baby potatoes",
    "rating": null,
    "recommendedBecause": "Available in the Natanya menu and not yet marked ordered.",
    "lastOrderedDate": "Never",
    "timesOrdered": 0,
    "davidNote": "",
    "lynnNote": "❤️"
  },
  {
    "id": "lowCalorie-chicken-fennel-and-cabbage-stew",
    "category": "lowCalorie",
    "description": "Chicken fennel and cabbage stew",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": "❤️ ❤️"
  },
  {
    "id": "lowCalorie-marinated-chicken-with-orange-beet-and-carrot-salad",
    "category": "lowCalorie",
    "description": "Marinated chicken with orange beet and carrot salad",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": "❤️"
  },
  {
    "id": "lowCalorie-grilled-chicken-roasted-sweet-potato-apple-cabbage-salad-with-hummus-dressing",
    "category": "lowCalorie",
    "description": "Grilled chicken roasted sweet potato apple cabbage salad with hummus dressing",
    "rating": null,
    "recommendedBecause": "Ordered before and available in the Natanya menu.",
    "lastOrderedDate": "Previously ordered",
    "timesOrdered": 1,
    "davidNote": "",
    "lynnNote": ""
  }
]
